In [23]:
import pandas as pd
df = pd.read_csv("StudentAddresses.csv")
print(df.head())

  6a. street # 6b. street name 6c. street suffix 6d. unit # 6e. zip  \
0           10         Higgins                ST        NaN    2134
1           10         Higgins                ST        NaN    2134
2         1189    Commonwealth               AVE          6    2134
3           12       Glenville               AVE        NaN    2134
4           12       Glenville               AVE          1    2134

  7. undergraduate (u) or graduate (g) 8. full-time (ft) or part-time (pt)  \
0                                    U                                  FT
1                                    U                                  FT
2                                    U                                  FT
3                                    U                                  FT
4                                    U                                  FT

  9. at-home or not-at-home 9. 5 or more undergrads/unit (y/n)  \
0                       NaN                                NaN
1                       NaN                                NaN
2                       NaN                                NaN
3                       NaN                                NaN
4                       NaN                                NaN

         university       year
0  Emmanuel College  2018-2019
1  Emmanuel College  2018-2019
2  Emmanuel College  2018-2019
3  Emmanuel College  2018-2019
4  Emmanuel College  2018-2019

/var/folders/5r/xpmg4qd96tb_5pks_bkh8z9w0000gn/T/ipykernel_13809/1804922737.py:2: DtypeWarning: Columns (4,7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("StudentAddresses.csv")

In [24]:
# Rename columns
df = df.rename(columns={
    '6a. street #': 'Street #',
    '6b. street name': 'Street Name',
    '6c. street suffix': 'Street Suffix',
    '6d. unit #': 'Unit #',
    '6e. zip': 'Zip'
})
df.head()

,Street #,Street Name,Street Suffix,Unit #,Zip,7. undergraduate (u) or graduate (g),8. full-time (ft) or part-time (pt),9. at-home or not-at-home,9. 5 or more undergrads/unit (y/n),university,year
0,10,Higgins,ST,NaN,2134,U,FT,NaN,NaN,Emmanuel College,2018-2019
1,10,Higgins,ST,NaN,2134,U,FT,NaN,NaN,Emmanuel College,2018-2019
2,1189,Commonwealth,AVE,6,2134,U,FT,NaN,NaN,Emmanuel College,2018-2019
3,12,Glenville,AVE,NaN,2134,U,FT,NaN,NaN,Emmanuel College,2018-2019
4,12,Glenville,AVE,1,2134,U,FT,NaN,NaN,Emmanuel College,2018-2019

Heres an example of the format of the table. What I need is 2 things--> One table with combined address values (one address column concatinatng "6a. street #" "6b. street name" , "6c. street suffix", "6d. unit #", "6e. zip" and then 2. I need another table with the rows where there was either

In [25]:
df = df[df['year'] == '2023-2024']

In [26]:
unique_suffixes = df['Street Suffix'].dropna().unique().tolist()
print((unique_suffixes))

['St', 'Pl', 'Rd', 'Ave', 'Terrace', 'Ct', 'E', 'W', 'Dr', 'Park', 'Way', 'Pi', 'Sq', 'Parkway', 'Circuit', 'Blvd', 'Mall', 'Street', 'Avenue', 'Drive', 'place', 'Road', 'Dalton Street', 'Emerson Place', 'Everett St.', 'Portina Rd.', 'Portina Road', 'Washington Mall', 'Chestnut Hill Ave', 'Commercial Wharf W', 'Eulita Terrace', 'Garden Court Street', 'Glenmont Road', 'JOHN A ANDREW ST.', 'Lake Shore Terrace', 'Orkney road', 'Orkney Road', 'Bowdoin st', 'Camelot court', 'Main St', 'Nottinghill Rd', 'Pier 4 blvd', 'Chestnut Street', 'Lanark Rd', 'Lanark Road', 'Dustin St.', 'Cass Street', 'Ninth St', 'Commonwealth Ave', 'Commonwealth Avenue', 'Academy hill RD', 'Academy Hill Rd', 'Jersey St', 'Queensberry St', 'Tremont St', 'Barrows Street', 'Breck Ave', 'Camelot Court', 'Camelot Ct', 'Commonwealth Ct', 'Embassy Rd', 'Kilsyth Terrace', 'Mount Hood Rd', 'Pasadena Rd', 'Ransom Rd', 'Walley Street', 'Kittredge St', 'Dustin St', 'Kilsyth Rd', 'Kilsyth Road', 'Ocean Street', 'Revere St.', 'Strathmore Road', 'Beacon Street', 'Washington St', 'Washington Street', 'Sutherland Rd', 'Charles Street', 'Dorchester St.', 'Sutherland Rd.', 'Sutherland Road', 'Sutherland road', 'Dorr St', 'Fairbanks St', 'Gardner Street', 'Humboldt Place', 'Glenville Ave', 'Tremont Street', 'Sutherland rd', 'Commonweath Ave', 'Lake Shore Road', 'Chiswick Rd', 'Chiswick Road', 'Guest St', 'Guest Street', 'Grew', 'Border Street', 'Lake Street', 'Marlborough Street', 'Nonantum St', 'Nonantum Street', 'Putnam St', 'Boylston St.', 'Boylston Street', 'Boylston st', 'Durnell Ave', 'Lake Shore Rd', 'Buswell Street', 'Mansfield St.', 'Englewood Ave', 'Englewood Avenue', 'Park Dr', 'Chiswick rd', 'Columbia Rd', 'Lake shore Rd', 'Seaport Blvd', 'Chiswick Rd.', 'CHISWICK RD', 'Peterborough Street', 'M Street', 'Washigton St.', 'Washington St.', 'Brighton st', 'Lake Shore Ct', 'Orkney Rd', 'Wallingford Rd', 'Woodward st', 'Kenrick St.', 'LAKE SHORE RD', 'Edgemere rd', 'Marine Road', 'Addison St.', 'Kenrick St', 'Kenrick Street', 'N Beacon St', 'Commercial St', 'Englewood Ave Apt 22', 'Englewood avenue', 'Chiswick', 'Chiswick Rd Apt', 'Chiwick Rd', 'Warren Ave', 'Carol Ave', 'Colliston Rd', 'Euston Rd', 'Euston Road', 'Montebello Rd.', 'N Beacon Street', 'Shepherd Ave', 'Commonwealth ave', 'commonwealth ave', 'Strathmore Rd', 'Lake Shore Rd.', 'Vfw Pkwy', 'Soldiers Field Rd', 'Soldiers Field RD', 'Soldiers Field Rd.', 'VFW Parkway', 'VFW PKWY', 'Lake shore road', 'Commonwealth Ave.', 'Kelton Street', 'Kelton St', 'Dorchester Street', 'Miner St', 'Rosemary Street', 'Washington St Apt', 'Allston Street', 'Commonwealth Avenue,', 'Ruthven St', 'Commonwealth AVE', 'Humboldt Ave', 'Admanson Street', 'Greymere Road', 'Lexington Street', 'Lothian Rd', 'Radcliffe Rd', 'Reedsdale Street', 'Salem Street', 'South Street', 'Washington st', 'Washington ST', 'WASHINGTON ST', 'Washington street', 'Cottage St', 'Blossom St', 'North Beacon St', 'Foster Street', 'Moultrie St', 'Radnor Road', 'Red Pine Rd', 'Green St', 'Telford St.', 'Telford Street', 'Allston St.', 'Laker Shore Road', 'Commonwealth avenue', 'Allston st.', 'Faneuil St', 'Foster Sreet', 'Foster St', 'North St', 'Bailey Street', 'Bennett Street', 'Braemore Rd', 'Bronsdon St', 'Donnybrook rd', 'Litchfield St', 'Perrin St', 'Turner St', 'Bellvista rd', 'Grampian Way', 'Foster St.', 'Strathmore Rd.', 'Normandy', 'Saint Botolph St', 'Beacon St', 'FOSTER STREET', 'Ayr Rd', 'Ayr Road', 'Colliston Road', 'Hawthorne Place', 'Holden Ct', 'LaRose Place', 'Menlo St', 'Ross Place', 'Brock St.', 'Cummings Road', 'Newcastle Rd', 'Penniman #P3', 'Brookline Ave', 'London St', 'West 8th Street', 'Marina Dr # U705W', 'Lake Shore', 'Corey Rd.', 'Wade St', 'Roslindale Ave', 'K Street', 'Market Street', 'W Broadway', 'Albany Street', 'Lakeshore Terrace', 'Wallingford Road', 'Kelton St.', 'KELTON STREET', 'Massachusetts Ave', 'Kelton', 'Centre St', 'Claymoss Rd', 'Newton St', 'Corey Rd', 'Corey Road', 'San Juan Street', 'Bigelow Street', 'Clark Street Boston', 'Colborne Rd', 'Colborne Rd.', 'Colborne Road', 'Adams Street', 'Brighton Ave.', 'Emerson Street', 'Chestnut Hill Ave.', 'Leyden Street', 'Allston street', 'Asheville Road', 'Boulevard Terrace', 'Fairbanks Street', 'Fort Ave', 'Jan Karski Way, #D536', 'Long Ave', 'Northern Ave', 'Cambridge St', 'Heath St', 'Chestnut Hill Avenue', 'W 3rd St', 'Bothwell RD', 'Commonwealth Terrace', 'Park Vale Ave', 'Park Vale Avenue', 'Faneuil Street', 'Princeton St', 'Bostonia Ave', 'Egleston St', 'Egremont Rd', 'Egremont Rd.', 'Justin Road', 'Vinton Street', 'Willoughby St', 'Chestnut Hill', 'Crosby Rd', 'Exeter Street', 'Sidlaw Rd', 'South Huntington Ave', 'Newbury street', 'Summit Ave', 'Hancock street', 'Fairbanks st', 'Summit Avenue', 'Carol Avenue', 'Algonquin St', 'Elmira street', 'Penniman Rd', 'Wade Street', 'Chelsea St', 'Lamartine St.', 'Lake Shore Court', 'A St', 'K Street Apt 1', 'N Harvard St', 'Summit ave', 'Garden Street  #B', 'Traveler St', 'Hanover Street', 'Wilson Park', 'Wiltshire Road', 'MARKET ST', 'Market street', 'SUMMIT AVE', 'E St.', 'Baker St.', 'Kirkwood', 'Kirkwood Rd.', 'Kirkwood Road', 'Lake shore terrace', 'Par Lane', 'Mount Vernon St', 'W 4th St', 'Linden street', 'Westmount Ave', 'Brooksdale Road', 'G St', 'N. Beacon st', 'Radnor Rd', 'Winton St', 'Chestnut Hill Av', 'Lake Shore Ter', 'Magnolia Street', 'Fordham Road', 'E 8th St', 'Claymoss Rd.', 'Shepard Street', 'Shepard Street A', 'Columbia Rd.', 'West Broadway', 'Cambridge Street', 'AYR RD', 'Ayr Rd.', 'Chestnut Pl', 'Chisholm Lane', 'Lucy st', 'Lucy Street', 'Maple Place', 'Price Rd', 'Price Road', 'Winship Pl', 'Winship Place', 'River street', 'UNION ST', 'Union Street', 'Union street', 'BROOKLINE AVE', 'West 1st Street', 'Dudley Street', 'Marlborough St', 'Atkins St', 'Farragut Rd', 'Lane Park', 'Lane Park Ave.', 'Gerrish St', 'STRATHMORE RD', 'POND ST', 'E 3rd St', 'East 3rd', 'South St.', 'Everett street', 'Kirkwood Rd', 'Cornwall Street', 'East Newton St', 'Province St', 'Stuart Street', 'Westland Ave', 'Bayard Street', 'St Stephen St', 'Harvest Street', 'Brighton Ave', 'Lanark road', 'Savin Hill Ave', 'Vine St', 'Fan Pier Blvd', 'Fan Pier Boulevard', 'Hull St', 'Lothian Road', 'Matchett Street', 'Royce Rd', 'Walbridge St', 'Walbridge St.', 'Wiget St', 'Causeway st', 'Chester', 'Leo M Birmingham Pkwy', 'Orton Marotta Way', 'Congress street', 'Congress St', 'E 4th St', 'Breck Avenue', 'Dickens St', 'Western Ave', 'Hopedale St.', 'E 7th Street', 'Gardner street', 'Hobart St', 'Riverdale St', 'Leamington road', 'Lake St', 'Brainerd Rd', 'Brainerd Road', 'Goodenough St.', 'Hull St.', 'Weld Street', 'Alcott Street', 'Cufflin Street', 'Moreland St', 'Pama Gardens', 'Parsons Street', 'Royal Street', 'E 4th Street', 'Columbus Ave', 'Surrey Street', 'Tonawanda Street', 'Woodstock Ave.', 'Corey rd', 'Langley Road', 'E 5th St', 'Joy Street', 'Kittredge St.', 'HUNTINGTON AVE', 'Huntington Ave.', 'Dorchester Avenue', 'Brooks Street', 'Mozart Street', 'Russell St', 'East Broadway', 'Romsey St', 'Nonantum St.', "William Cardinal O'Connel", 'Saint Botolph St.', 'East 8th Street', 'Argus place', 'Ascot St', 'Delaware Pl', 'Greenmount St.', 'Harvard Terrace', 'Harvard Terrace, Unit 1', 'Lorraine St', 'Mount Hood Road', 'Scottfield Road Apt 11', 'South Crescent Circuit', 'Strathmore rd', 'College Rd', 'Waumbeck St', 'Mapleton', 'Brooks St', 'Beacon Street.', 'Brainerd Rd.', 'Braintree St.', 'W School St', 'Dorchester Ave', 'Horace St', 'Boylston St', 'Smith Court', 'Cenacle Rd', 'Cenacle Road', 'Kinross Rd', 'Pleasant Street', 'Vinal St', 'Winter Street', 'Richardson St.', 'Academy Hill Road', 'Elmira St.', 'Brianerd Road', 'Hobart Street', 'Montclair Ave', 'E 1st St', 'Chester St', 'Salman street', 'Glencoe St', 'Brainerd', 'Undine Rd', 'BENNINGTON ST', 'DIX STREET', 'East Brookline St.', 'Nottinghill Road', 'Gordon St', 'Saint Alphonsus St', 'Linden Street', 'Hyde Park Ave', 'Chestnut Ave', 'Tremont St.', 'PO Box 35772', 'Private', 'St.', 'st', 'Place', 'Rd.', 'street', 'ST', 'Court', 'Ln', 'PL', 'terrace', 'rd', 'road', 'st.', 'Ter', 'RD', 'Boulevard', 'way', 'Pkwy', 'Pl.', 'Street South', 'STREET', 'Square', 'Ct.', 'Dr.', 'ct', 'Green', 'Ave.', 'dr', 'Row', 'ST.', 'ROAD', 'ter', 'CT', 'Highway', 'row', 'rd.', 'pl', 'BLVD', 'drive', 'DRIVE', 'DR', 'AVENUE', 'ave', 'PKWY', 'Plaza', 'sq', 'SQ', 'Wharf', 'Lane', 'Broadway', 'AVE', 'TERR', 'WAY', 'Grn', 'Terr', 'Cir', 'Circle', 'AVe', 'St,', 'West', 'park', 'Str', 'Rod', 'Vale', 'Pky', 'Ave,', 'Wy', 'Avenue,', 'Apt', 'Street,', 'Hwy', 'Sq.', 'Pllace', 'St.,', 'Ter.', 'Cir.', 'East', 'Street.', 'PARK', 'PK', 'PLACE', 'TER', 'MALL', 'LN', 'CIR', 'blvd', 'Pk', 'Gdns', 'Rdf', 'pk', 'Arch', 'Hill', 'Pt', 'Av+C+C133:C161', 'St S', 'square', 'Vernon']

In [27]:
df.head()

,Street #,Street Name,Street Suffix,Unit #,Zip,7. undergraduate (u) or graduate (g),8. full-time (ft) or part-time (pt),9. at-home or not-at-home,9. 5 or more undergrads/unit (y/n),university,year
159317,10,Rhoda St,NaN,NaN,2132,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159318,10,Rhoda Street,NaN,NaN,2132,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159319,580,Washington Street,NaN,NaN,2111,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159320,12,Sutherland Rd,NaN,3,2135,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159321,137,Chiswick rd,NaN,apt 5,2135,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024

In [28]:
df['Zip'] = df['Zip'].astype(str).str.zfill(5)

In [29]:
df.head()

,Street #,Street Name,Street Suffix,Unit #,Zip,7. undergraduate (u) or graduate (g),8. full-time (ft) or part-time (pt),9. at-home or not-at-home,9. 5 or more undergrads/unit (y/n),university,year
159317,10,Rhoda St,NaN,NaN,02132,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159318,10,Rhoda Street,NaN,NaN,02132,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159319,580,Washington Street,NaN,NaN,02111,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159320,12,Sutherland Rd,NaN,3,02135,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024
159321,137,Chiswick rd,NaN,apt 5,02135,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024

In [30]:
registry = pd.read_csv("current_rental_registrations_251001 2.csv")
print(registry.head())

     LICENSENO  SAMid  row_number_licenseno_SAMid  \
0  Rent-104588    NaN                         NaN
1  Rent-105479    NaN                         NaN
2  Rent-106123    NaN                         NaN
3  Rent-106123    NaN                         NaN
4  Rent-106166    NaN                         NaN

                             RegisteredAddress LICENSECAT OWNEROCC  \
0       54 Desoto RD  , WEST ROXBURY, MA 02132     1-3FAM        N
1  152H Chestnut AV  , Jamaica Plain, MA 02130     1-3FAM        N
2        103 Ninth ST  , Charlestown, MA 02129   MultiFam        N
3        103 Ninth ST  , Charlestown, MA 02129   MultiFam        N
4                                    ,  , MA       1-3FAM        Y

   NUMBEROFUNITS  TOTALUNITS            SystemAddDate  \
0              2           2  2013-08-20 09:47:26.000
1              2           2  2013-08-23 21:18:24.000
2            112         112  2013-08-27 10:49:42.000
3            112         112  2013-08-27 10:49:42.000
4              1           2  2013-08-27 11:22:58.000

                 IssueDate  ... ISLICENSEE contacttype ApplicantLastName  \
0  2022-03-10 12:39:42.000  ...          Y       AGENT        Sougarides
1  2013-08-23 21:20:26.000  ...          Y        HOME            Cronin
2  2013-10-15 15:22:41.000  ...          N       OWNER            Barkan
3  2013-10-15 15:22:41.000  ...          Y                         Moser
4  2013-08-27 11:24:34.000  ...          Y                       Camacho

  ApplicantFirstName             ApplicantAddress ApplicantAddress2  \
0              Peter               54 Desoto Road               NaN
1               Jeff  152 Chestnut Avenue, Apt. 1               NaN
2              Peter               7 Wells Avenue          Suite 11
3             Hannah             103 Ninth Street               NaN
4           Laylanni                 19 Harlem St               NaN

   ApplicantCity ApplicantState ApplicantPhone  \
0   West Roxbury             MA  (617)875-3666
1  Jamaica Plain             MA  (626)437-7957
2         Newton             MA  (617)532-8605
3    Charlestown             MA  (617)242-4515
4         Boston             MA  (617)953-2825

                                     ApplicantEmail
0                         psougarides@samuelsre.com
1                                clancy_101@msn.com
2                              pbarkan@barkanco.com
3  manager.anchorageapartments@barkanmanagement.com
4                        laylanni.camacho@gmail.com

[5 rows x 27 columns]

In [36]:
unique_addreses = registry['RegisteredAddress'].dropna().unique().tolist()
print(unique_addreses)

['54 Desoto RD  , WEST ROXBURY, MA 02132', '152H Chestnut AV  , Jamaica Plain, MA 02130', '103 Ninth ST  , Charlestown, MA 02129', '       ,  , MA  ', '1912-1914 BEACON ST ST  , BOSTON, MA 02135', '10 Thacher ST  , Boston/North End, MA 02113', '50 Adams ST  , DORCHESTER, MA 02122', '6 ODonnell TE  , Dorchester, MA 02122', '42 Park ST  , Charlestown, MA 02129', '330A-332 North ST  , North end, MA 02113', '372-382 Warren ST  , ROXBURY, MA 02119', '768 Huntington AV  , Boston, MA 02115', '449-451 walnut AV  , roxbury, MA 02119', '819 E Fourth ST  , SOUTH BOSTON, MA 02127', '234-238 Hanover ST  , Boston, MA 02113', '90-100 Washington ST  , Dorchester, MA 02125', '2-4 Sojourner Truth CT  , BOSTON, MA 02119', '159 Dewitt DR  , Roxbury, MA 02120', '30 Washington ST  , Allston, MA 02135', '48 School ST  , Jamaica Plain, MA 02130', '1130 Washington ST  , Dorchester, MA 02124', '1 Charles ST  , Boston/Beacon Hill, MA 02108', '1 Charles Street South    , Boston, MA 02116', '11 appian way    , BOSTON, MA  ', '860 Harrison AV  , BOSTON/, MA 02118', '12A Partridge ST  , West Roxbury, MA 02132', '296-298 Wood AV  , HYDE PARK, MA 02136', '2 Copps Hill TE  , North End, MA 02113', '4 COPPS HILL TE , BOSTON, MA 02113', '6 Dunkeld ST  , Dorchester, MA 02121', '8 Dunkeld ST  , Dorchester, MA 02121', '10 Dunkeld ST  , Dorchester, MA 02121', '85 E INDIA RO 37-B, BOSTON, MA 02110', '74 Desoto RD  , West Roxbury, MA 02132', '58 Winston RD  , Dorchester, MA 02124', '109 Dakota ST  , Dorchester, MA 02124', '628-630 TREMONT ST ST  , BOSTON, MA 02118', '328-330 Shawmut AV  , Boston, MA 02118', '1906-1918 Dorchester AV  , Dorchester, MA 02124', '46-52 san juan ST  , Boston, MA 02118', '375 Columbus AV  , Boston, MA 02116', '465 Columbus AV  , Boston, MA 02118', '20 FOWLER ST ST  , BOSTON, MA 02121', '42-46 Whitfield ST  , Dorchester, MA 02124', '172 W Springfield ST  , Boston, MA 02118', '46-48 Saybrook ST  , Brighton, MA 02135', '75 W Dedham ST  , South End, MA 02118', '59-69 Msgr P J Lydon WA  , Dorchester, MA 02124', '10-12 Wales ST  , DORCHESTER, MA 02124', '60 Joy    , Boston, MA  ', '85 E INDIA RO 36-D, BOSTON, MA 02110', '2053R Columbus AVE  , Roxbury, MA 02119', '2875 washington    , roxbury, MA 02119', '208-210 Hampden ST  , Roxbury/, MA 02119', '9 Warwick ST  , ROXBURY, MA 02120', '74-74B Oakland ST  , Brighton, MA 02135', '148-152 Dorchester AV 509, South Boston, MA 02127', '220-240 Hanover ST  , Boston, MA  ', '65 E INDIA RO 10F, BOSTON, MA 02110', '80 White ST  , East Boston, MA 02128', '458 Washington ST  , Brighton, MA 02135', '201-205 SOUTH HUNTINGTON    , JAMAICA PLAIN, MA 02130', '89 W Dedham ST  , South End, MA 02118', '17R Albion ST  , Roxbury, MA 02119', '245 N BEACON ST , BRIGHTON, MA 02135', '7-3 TEMPLE ST ST  , BOSTON, MA 02129', '4 Dunkeld ST  , Dorchester, MA 02121', '8 Griggs ST  , ALLSTON, MA 02134', '11 Delle AV  , Roxbury, MA 02120', '3-5 MT PLEASANT AV AV  , BOSTON, MA 02119', '1259-1261 Dorchester AV  , DORCHESTER, MA 02122', '160 Commonwealth AV 704, BOSTON, MA 02116', '230 SUMNER ST  , East Boston, MA 02128', '3 WEBSTER PL  , NorthEnd, MA 02113', '375-381 MT VERNON ST  , Dorchester, MA 02125', '22-24 FAYSTON ST  , Dorchester, MA 02121', '5-7 NEPTUNE CI  , East Boston, MA 02128', '35 TYLER ST  , Chinatown, MA 02111', '11 KENNEY ST  , Mission Hill, MA 02120', '44 ELLINGTON ST  , Dorchester, MA 02121', '200-204 COMMONWEALTH AV  , Boston, MA 02116', '120-122 MADISON PARK CT  , Roxbury, MA 02119', '134-142 MADISON PARK CT  , Roxbury, MA 02119', '1255 ADAMS ST  , Dorchester Center, MA 02124', '23 FOLLEN ST  , Boston, MA 02116', '53 PRESCOTT ST  , East Boston, MA 02128', '92-94 MOZART ST  , Mission Hill, MA 02120', '40 LARCH ST  , Brighton, MA 02135', '5B MILL ST  ,  , MA 02122', '7 DUNKELD ST  , Dorchester, MA 02121', '6 WELLINGTON CT  , Roxbury, MA 02119', '7 WELLINGTON CT  , Roxbury, MA 02119', '8 WELLINGTON CT  , Roxbury, MA 02119', '21 FRONTENAC ST  , Dorchester Center, MA 02124', '25 FRONTENAC ST  , Dorchester Center, MA 02124', '133 LUCERNE ST  , Dorchester Center, MA 02124', '135 LUCERNE ST  , Dorchester Center, MA 02124', '141 LUCERNE ST  , Dorchester Center, MA 02124', '137 LUCERNE ST  , Dorchester Center, MA 02124', '11-15 LORNE ST  , Dorchester Center, MA 02124', '82-84 COLBORNE RD  , Brighton, MA 02135', '219 DELHI ST  , Hyde Park, MA 02136', '25 ROCKVALE CI  , Jamaica Plain, MA 02130', '27 ROCKVALE CI  , Jamaica Plain, MA 02130', '29 ROCKVALE CI  , Jamaica Plain, MA 02130', '31 ROCKVALE CI  , Jamaica Plain, MA 02130', '11 WESTMINSTER ST  , Roxbury, MA 02119', '11-13 MULVEY ST  , Hyde Park, MA 02136', '1734-1740 WASHINGTON ST  , Roxbury, MA 02119', '65 BRAINERD RD  , Allston, MA 02134', '1940 COMMONWEALTH AV  , Brighton, MA 02135', '221 RIVER ST  , Hyde Park, MA 02136', '201 HARVARD AV  , Allston, MA 02134', '39-41 Cherokee ST  , Mission Hill, MA 02120', '4 WELLINGTON CT  , Roxbury, MA 02119', '10 ELLET ST  , Dorchester, MA 02122', '91 MOZART ST  , Jamaica Plain, MA 02130', '160 N BEACON ST  , Brighton, MA 02135', '5 BRAEMORE RD  , Brighton, MA 02135', '891 HUNTINGTON AV  , Mission Hill, MA 02120', '895 HUNTINGTON AV  , Mission Hill, MA 02120', '29 MT HOOD RD  , Brighton, MA 02135', '36 Mystic ST 1, Charlestown, MA 02129', '190 Beacon ST 5, Boston, MA 02116', '42 Mystic ST , Charlestown, MA 02129', '43 Mystic ST , Charlestown, MA 02129', '190 Beacon ST 6, Boston, MA 02116', '50 Mystic ST 1, Charlestown, MA 02129', '190 Beacon ST 7, Boston, MA 02116', '106 N ST , South Boston, MA 02127', '107 N ST , South Boston, MA 02127', '113-115 N ST 2, South Boston, MA 02127', '119 N ST 1, South Boston, MA 02127', '119 N ST 2, South Boston, MA 02127', '135 N ST , South Boston, MA 02127', '145 N ST , South Boston, MA 02127', '155 N ST , South Boston, MA 02127', '157 N ST , South Boston, MA 02127', '192 Beacon ST 3, Boston, MA 02116', '201-203 N ST , South Boston, MA 02127', '211-213 N ST , South Boston, MA 02127', '42 N ST , South Boston, MA 02127', '48 N ST , South Boston, MA 02127', '52 N ST , South Boston, MA 02127', '66 N ST 6, South Boston, MA 02127', '24 Nahant AVE , Dorchester, MA 02122', '36 Nahant AV 14, Dorchester, MA 02122', '193 Beacon ST 2, Boston, MA 02116', '10 Nantasket AV , Brighton, MA 02135', '6-8 Narragansett ST , Dorchester, MA 02122', '9-11 Narragansett ST , Dorchester, MA 02122', '1 Nassau ST , Boston, MA 02111', '1 Nassau ST 1009, Boston, MA 02111', '194 Beacon ST 1, Boston, MA 02116', '1 Nassau ST 1209, Boston, MA 02111', '194 Beacon ST 3, Boston, MA 02116', '194 Beacon ST 4, Boston, MA 02116', '194 Beacon ST 5, Boston, MA 02116', '1 Nassau ST 1703, Boston, MA 02111', '195 Beacon ST 1, Boston, MA 02116', '1 Nassau ST 2106, Boston, MA 02111', '1 Nassau ST 2205, Boston, MA 02111', '1 Nassau ST 2207, Boston, MA 02111', '12 National ST A, South Boston, MA 02127', '14 National ST , South Boston, MA 02127', '18 National ST , South Boston, MA 02127', '140 Navarre ST , Hyde Park, MA 02136', '145 Navarre ST , Hyde Park, MA 02136', '55 Navarre ST , Roslindale, MA 02131', '11 Navillus TER  , Dorchester, MA 02122', '12 Navillus TER , Dorchester, MA 02122', '4-6 Navillus TER , Dorchester, MA 02122', '5 Navillus TER , Dorchester, MA 02122', '7 Navillus TER , Dorchester, MA 02122', '1-8 Nazing CT , Dorchester, MA 02121', '14-16 Nazing ST , Dorchester, MA 02121', '2-4 Nazing ST , Dorchester, MA 02121', '21 Nazing ST , Dorchester, MA 02121', '25 Nazing ST , Dorchester, MA 02121', '30 Nazing ST , Dorchester, MA 02121', '31 Nazing ST 1, Dorchester, MA 02121', '39 Nazing ST , Dorchester, MA 02121', '43 Nazing ST , Dorchester, MA 02121', '47 Nazing ST , Dorchester, MA 02121', '108 Needham RD , Hyde Park, MA 02136', '119 Needham RD , Hyde Park, MA 02136', '197 Beacon ST , Boston, MA 02116', '84 Needham RD , Hyde Park, MA 02136', '96 Needham RD , Hyde Park, MA 02136', '199 Beacon ST , Boston, MA 02116', '18 Nelson ST , Dorchester, MA 02124', '21-23 Nelson ST , Dorchester, MA 02124', '25 Nelson ST , Dorchester, MA 02124', '26 Nelson ST , Dorchester, MA 02124', '33 Nelson ST , Dorchester, MA 02124', '4-6 Nelson ST , Dorchester, MA 02124', '50 Nelson ST , Dorchester, MA 02124', '56 Nelson ST , Dorchester, MA 02124', '7 Nelson ST , Dorchester, MA 02124', '75 Nelson ST , Dorchester, MA 02124', '8-10 Nelson ST , Dorchester, MA 02124', '82 Nelson ST , Dorchester, MA 02124', '9-11 Nelson ST , Dorchester, MA 02124', '17 Neponset AV , Hyde Park, MA 02136', '23 Neponset AV , Hyde Park, MA 02136', '27 Neponset AV , Roslindale, MA 02131', '34 Neponset AV , Hyde Park, MA 02136', '39 Neponset AV , Hyde Park, MA 02136', '40 Neponset AV , Hyde Park, MA 02136', '57 Neponset AV , Hyde Park, MA 02136', '58 Neponset AV , Hyde Park, MA 02136', '59 Neponset AV , Hyde Park, MA 02136', '61 Neponset AV , Hyde Park, MA 02136', '63 Neponset AV , Hyde Park, MA 02136', '66 Neponset AV , Hyde Park, MA 02136', '68 Neponset AV , Hyde Park, MA 02136', '72 Neponset AV , Hyde Park, MA 02136', '87-89 Neponset AV , Roslindale, MA 02131', '58 Neponset AV , Roslindale, MA 02131', '60 Neponset AV , Roslindale, MA 02131', '91 Adams ST , Dorchester, MA 02122', '105 Neponset AVE , Dorchester, MA 02122', '204 Beacon ST 2-F, Boston, MA 02116', '124 Neponset AVE , Dorchester, MA 02122', '126 Neponset AVE , Dorchester, MA 02122', '135 Neponset AV 1, Dorchester, MA 02122', '135 Neponset AV 2, Dorchester, MA 02122', '135 Neponset AV 24, Dorchester, MA 02122', '135 Neponset AV 31, Dorchester, MA 02122', '135 Neponset AV 32, Dorchester, MA 02122', '135 Neponset AV 33, Dorchester, MA 02122', '135 Neponset AV 34, Dorchester, MA 02122', '135 Neponset AV 43, Dorchester, MA 02122', '135 Neponset AV 46, Dorchester, MA 02122', '151-161 Neponset AVE , Dorchester, MA 02122', '205 Beacon ST , Boston, MA 02116', '16 Neponset AVE , Dorchester, MA 02122', '215 Neponset AVE , Dorchester, MA 02122', '217 Neponset AV 22, Dorchester, MA 02122', '218 Neponset AVE , Dorchester, MA 02122', '23 Neponset AVE , Dorchester, MA 02122', '266 Neponset AVE , Dorchester, MA 02122', '273 Neponset AVE , Dorchester, MA 02122', '289-291 Neponset AVE , Dorchester, MA 02122', '304-304A Neponset AV , Dorchester, MA 02122', '327 Neponset AVE , Dorchester, MA 02122', '209 Beacon ST , Boston, MA 02116', '345-345A Neponset AV , Dorchester, MA 02122', '37 Neponset AVE , Dorchester, MA 02122', '39 Neponset AVE , Dorchester, MA 02122', '400-412 Neponset AVE , Dorchester, MA 02122', '41 Neponset AVE , Dorchester, MA 02122', '21 Beacon ST 2-B, Boston, MA 02108', '46 Neponset AVE , Dorchester, MA 02122', '54 Neponset AVE , Dorchester, MA 02122', '69 Neponset AVE , Dorchester, MA 02122', '85 Neponset AVE , Dorchester, MA 02122', '86-90 Neponset AVE , Dorchester, MA 02122', '91 Neponset AVE , Dorchester, MA 02122', '161 Neponset Valley PW , Hyde Park, MA 02136', '204 Neponset Valley PW , Hyde Park, MA 02136', '312 Neponset Valley PW , Hyde Park, MA 02136', '10-12 Neptune CI , East Boston, MA 02128', '14-16 Neptune CI , East Boston, MA 02128', '22-24 Abbotsford ST , Dorchester, MA 02121', '14 New England AV , Dorchester, MA 02124', '18-20 New England AV , Dorchester, MA 02124', '21 Beacon ST 3-K, Boston, MA 02108', '115-117 New Haven ST , West Roxbury, MA 02132', '21 Beacon ST 3-R, Boston, MA 02108', '7 New Haven ST , West Roxbury, MA 02132', '28 Newbern ST 28-3, Jamaica Plain, MA 02130', '21 Beacon ST 4-E, Boston, MA 02108', '100 Newburg ST , Roslindale, MA 02131', '24 Newburg ST , Roslindale, MA 02131', '36 Newburg ST , Roslindale, MA 02131', '37 Newburg ST , Roslindale, MA 02131', '64 Newburg ST , Roslindale, MA 02131', '65 Newburg ST , Roslindale, MA 02131', '8 Newburg ST , Roslindale, MA 02131', '87 Newburg ST , Roslindale, MA 02131', '110 Newbury ST , Boston, MA 02116', '112 Newbury ST , Boston, MA 02116', '21 Beacon ST 4-N, Boston, MA 02108', '114 Newbury ST , Boston, MA 02116', '119 Newbury ST , Boston, MA 02116', '123 Newbury ST , Boston, MA 02116', '128 Newbury ST , Boston, MA 02116', '130 Newbury ST , Boston, MA 02116', '131 Newbury ST , Boston, MA 02116', '154 Newbury ST , Boston, MA 02116', '21 Beacon ST 4-S, Boston, MA 02108', '160 Newbury ST , Boston, MA 02116', '163 Newbury ST , Boston, MA 02116', '166 Newbury ST , Boston, MA 02116', '173 Newbury ST , Boston, MA 02116', '174 Newbury ST , Boston, MA 02116', '175 Newbury ST , Boston, MA 02116', '177 Newbury ST , Boston, MA 02116', '21 Beacon ST 5-B, Boston, MA 02108', '939-941 Adams ST , Dorchester, MA 02124', '201 Newbury ST 305, Boston, MA 02116', '201 Newbury ST 402, Boston, MA 02116', '201 Newbury ST 503, Boston, MA 02116', '209 Newbury ST , Boston, MA 02116', '213 Newbury ST , Boston, MA 02116', '219 Newbury ST , Boston, MA 02116', '220 Newbury ST , Boston, MA 02116', '221 Newbury ST , Boston, MA 02116', '21 Beacon ST 5-G, Boston, MA 02108', '223 Newbury ST , Boston, MA 02116', '225 Newbury ST , Boston, MA 02116', '227 Newbury ST , Boston, MA 02116', '247 Newbury ST , Boston, MA 02116', '250 Newbury ST , Boston, MA 02116', '252 Newbury ST , Boston, MA 02116', '253 Newbury ST , Boston, MA 02116', '254 Newbury ST , Boston, MA 02116', '255 Newbury ST , Boston, MA 02116', '263 Newbury ST , Boston, MA 02116', '264 Newbury ST , Boston, MA 02116', '267 Newbury ST , Boston, MA 02116', '269 Newbury ST , Boston, MA 02116', '270 Newbury ST , Boston, MA 02116', '280 Newbury ST , Boston, MA 02116', '282 Newbury ST , Boston, MA 02116', '282 Newbury ST 1, Boston, MA 02116', '282 Newbury ST 5, Boston, MA 02116', '282 Newbury ST 6, Boston, MA 02116', '282 Newbury ST 8, Boston, MA 02116', '282 Newbury ST 9, Boston, MA 02116', '282 Newbury ST 10, Boston, MA 02116', '21 Beacon ST 5-N, Boston, MA 02108', '287 Newbury ST , Boston, MA 02115', '290 Newbury ST , Boston, MA 02115', '291 Newbury ST , Boston, MA 02115', '293 Newbury ST , Boston, MA 02115', '295 Newbury ST , Boston, MA 02115', '299 Newbury ST , Boston, MA 02115', '301 Newbury ST , Boston, MA 02115', '21 Beacon ST 5-R, Boston, MA 02108', '304 Newbury ST , Boston, MA 02115', '306 Newbury ST , Boston, MA 02115', '308 Newbury ST , Boston, MA 02115', '314 Newbury ST , Boston, MA 02115', '328 Newbury ST , Boston, MA 02115', '21 Beacon ST 6-B, Boston, MA 02108', '360 Newbury ST 404, Boston, MA 02115', '360 Newbury ST 611, Boston, MA 02115', '21 Beacon ST 6-G, Boston, MA 02108', '21 Beacon ST 6-I, Boston, MA 02108', '95 Adams ST , Dorchester, MA 02122', '21 Beacon ST 6-Q, Boston, MA 02108', '21 Beacon ST 7-G, Boston, MA 02108', '973-975 Adams ST , Dorchester, MA 02124', '21 Beacon ST 7-S, Boston, MA 02108', '525 Newbury ST , Boston, MA 02215', '531 Newbury ST , Boston, MA 02215', '533 Newbury ST , Boston, MA 02215', '535 Newbury ST , Boston, MA 02215', '21 Beacon ST 8-E, Boston, MA 02108', '81 Newbury ST , Boston, MA 02116', '977-979 Adams ST , Dorchester, MA 02124', '15-17 Newcastle RD , Brighton, MA 02135', '16-18 Newcastle RD , Brighton, MA 02135', '27-29 Newcastle RD , Brighton, MA 02135', '28-30 Newcastle RD , Brighton, MA 02135', '31-33 Newcastle RD , Brighton, MA 02135', '47-49 Newcastle RD , Brighton, MA 02135', '7-9 Newcastle RD , Brighton, MA 02135', '11 Newcomb ST , Roxbury, MA 02118', '15 Newcroft CI , Mattapan, MA 02126', '16 Newcroft CI , Mattapan, MA 02126', '19 Newcroft CI , Mattapan, MA 02126', '27 Newcroft CI , Mattapan, MA 02126', '31 Newcroft CI , Mattapan, MA 02126', '39 Newcroft CI , Mattapan, MA 02126', '43 Newcroft CI , Mattapan, MA 02126', '48 Newcroft CI , Mattapan, MA 02126', '48 Newfield ST , West Roxbury, MA 02132', '21 Beacon ST 8-T, Boston, MA 02108', '9-11 Newhall PL , Dorchester, MA 02122', '41 Newhall ST , Dorchester, MA 02122', '21 Beacon ST 9-D, Boston, MA 02108', '21 Beacon ST 9-E, Boston, MA 02108', '11 Newport ST , Dorchester, MA 02125', '26 Newport ST , Dorchester, MA 02125', '35 Newport ST , Dorchester, MA 02125', '40 Newport ST , Dorchester, MA 02125', '41-43 Newport ST , Dorchester, MA 02125', '42 Newport ST , Dorchester, MA 02125', '44 Newport ST , Dorchester, MA 02125', '9 Newport ST , Dorchester, MA 02125', '11-13 Newsome PK , Jamaica Plain, MA 02130', '7-9 Newsome PK , Jamaica Plain, MA 02130', '11 Newton ST , Brighton, MA 02135', '140 Newton ST 140-3, Brighton, MA 02135', '21 Beacon ST 9-N, Boston, MA 02108', '144 Newton ST 144-1, Brighton, MA 02135', '144 Newton ST 144-3, Brighton, MA 02135', '21 Beacon ST 9-P, Boston, MA 02108', '15 Newton ST , Brighton, MA 02135', '152 Newton ST 152-3, Brighton, MA 02135', '156 Newton ST 156-2, Brighton, MA 02135', '160 Newton ST 160-4, Brighton, MA 02135', '164 Newton ST 164-2, Brighton, MA 02135', '164 Newton ST 164-4, Brighton, MA 02135', '168 Newton ST 168-1, Brighton, MA 02135', '168 Newton ST 168-2, Brighton, MA 02135', '168 Newton ST 168-4, Brighton, MA 02135', '168 Newton ST 168-5, Brighton, MA 02135', '168 Newton ST 168-6, Brighton, MA 02135', '172 Newton ST 172-2, Brighton, MA 02135', '184 Newton ST 184-4, Brighton, MA 02135', '188 Newton ST 188-6, Brighton, MA 02135', '25 Newton ST , Brighton, MA 02135', '27 Newton ST , Brighton, MA 02135', '31 Newton ST , Brighton, MA 02135', '35 Newton ST , Brighton, MA 02135', '38 Newton ST , Brighton, MA 02135', '40 Newton ST , Brighton, MA 02135', '44 Newton ST 44, Brighton, MA 02135', '34 E Newton ST 34-3, Roxbury, MA 02118', '34 E Newton ST 34-5, Roxbury, MA 02118', '34 E Newton ST 34-8, Roxbury, MA 02118', '45 E Newton ST RESIDENTAL, Roxbury, MA 02118', '21 Beacon ST 11-C, Boston, MA 02108', '115 W Newton ST , Roxbury, MA 02118', '119 W Newton ST , Roxbury, MA 02118', '122 W Newton ST , Roxbury, MA 02118', '125 W Newton ST , Roxbury, MA 02118', '127 W Newton ST , Roxbury, MA 02118', '128 W Newton ST , Roxbury, MA 02118', '130 W Newton ST , Roxbury, MA 02118', '131 W Newton ST , Roxbury, MA 02118', '133 W Newton ST , Roxbury, MA 02118', '134 W Newton ST , Roxbury, MA 02118', '147 W Newton ST , Roxbury, MA 02118', '159 W Newton ST , Roxbury, MA 02118', '172 W Newton ST , Roxbury, MA 02118', '197 W Newton ST 4, Boston, MA 02116', '199 W Newton ST 3, Boston, MA 02116', '201 W Newton ST , Boston, MA 02116', '209 W Newton ST , Boston, MA 02116', '211 W Newton ST 1, Boston, MA 02116', '211 W Newton ST 2, Boston, MA 02116', '213 W Newton ST , Boston, MA 02116', '215 W Newton ST , Boston, MA 02116', '219 W Newton ST 1, Boston, MA 02116', '219 W Newton ST 2, Boston, MA 02116', '219 W Newton ST 4, Boston, MA 02116', '221-221A W Newton ST , Boston, MA 02116', '233 W Newton ST , Boston, MA 02116', '235 W Newton ST , Boston, MA 02116', '211 Beacon ST , Boston, MA 02116', '236 W Newton ST 1, Boston, MA 02115', '236 W Newton ST 2, Boston, MA 02115', '239 W Newton ST , Boston, MA 02116', '241 W Newton ST , Boston, MA 02116', '242 W Newton ST 242-1, Boston, MA 02115', '242 W Newton ST 242-2, Boston, MA 02115', '213 Beacon ST , Boston, MA 02116', '243 W Newton ST 3, Boston, MA 02116', '243 W Newton ST 6, Boston, MA 02116', '245 W Newton ST 245-2, Boston, MA 02116', '215 Beacon ST , Boston, MA 02116', '259 W Newton ST , Boston, MA 02116', '1 Adamson ST , Allston, MA 02134', '37 W Newton ST 6, Roxbury, MA 02118', '42 W Newton ST B-5, Roxbury, MA 02118', '42 W Newton ST 4-23, Roxbury, MA 02118', '43 W Newton ST B-3, Roxbury, MA 02118', '216 Beacon ST 3, Boston, MA 02116', '217 Beacon ST , Boston, MA 02116', '104 Nightingale ST , Dorchester, MA 02124', '11 Nightingale ST , Dorchester, MA 02124', '15 Nightingale ST , Dorchester, MA 02124', '19 Nightingale ST , Dorchester, MA 02124', '21 Nightingale ST , Dorchester, MA 02124', '23 Nightingale ST , Dorchester, MA 02124', '28 Nightingale ST , Dorchester, MA 02124', '29 Nightingale ST , Dorchester, MA 02124', '3-1 Nightingale ST , Dorchester, MA 02124', '30 Nightingale ST , Dorchester, MA 02124', '35 Nightingale ST , Dorchester, MA 02124', '36 Nightingale ST , Dorchester, MA 02124', '46 Nightingale ST , Dorchester, MA 02124', '53 Nightingale ST , Dorchester, MA 02124', '65-69 Nightingale ST 4A, Dorchester, MA 02124', '77-79 Nightingale ST , Dorchester, MA 02124', '9 Nightingale ST , Dorchester, MA 02124', '90 Nightingale ST , Dorchester, MA 02124', '91 Nigh

In [34]:
suffix_clean_map = {
    # Street
    "st": "Street", "st.": "Street", "street": "Street", "street.": "Street",
    "st,": "Street", "str": "Street", "st s": "Street", "st,": "Street",
    "st.": "Street", "street,": "Street", "st.": "Street",

    # Road
    "rd": "Road", "rd.": "Road", "road": "Road", "rd,": "Road",

    # Avenue
    "ave": "Avenue", "ave.": "Avenue", "avenue": "Avenue", "avenue,": "Avenue",
    "ave,": "Avenue", "av": "Avenue", "ave.": "Avenue", "ave": "Avenue",

    # Drive
    "dr": "Drive", "dr.": "Drive", "drive": "Drive",

    # Boulevard
    "blvd": "Boulevard", "blvd.": "Boulevard", "boulevard": "Boulevard",

    # Place
    "pl": "Place", "pl.": "Place", "place": "Place", "pll": "Place",
    "pll.": "Place", "pllace": "Place", "pl,": "Place", "plaza": "Place",

    # Court
    "ct": "Court", "ct.": "Court", "court": "Court",

    # Terrace
    "terrace": "Terrace", "ter": "Terrace", "ter.": "Terrace", "terr": "Terrace",

    # Lane
    "ln": "Lane", "ln.": "Lane", "lane": "Lane",

    # Circle
    "cir": "Circle", "circle": "Circle", "cir.": "Circle",

    # Parkway
    "pkwy": "Parkway", "pkway": "Parkway", "pk": "Parkway", "pky": "Parkway",
    "pkwy.": "Parkway", "vfw pkwy": "Parkway",

    # Square
    "sq": "Square", "sq.": "Square", "square": "Square",

    # Mall
    "mall": "Mall",

    # Row
    "row": "Row",

    # Highway
    "hwy": "Highway", "highway": "Highway",

    # Way
    "way": "Way", "way.": "Way",

    # Wharf
    "wharf": "Wharf",

    # Park
    "park": "Park",

    # Court variant
    "crt": "Court", "cty": "Court",

    # Other cleanup categories
    "apt": "Apartment", "unit": "Unit",
    "other": "Other", "unknown": "Unknown"
}


# Function to clean and normalize suffix
def clean_suffix(suffix):
    if not isinstance(suffix, str):
        return "Unknown"
    cleaned = suffix.strip().lower().replace('.', '').replace(',', '')
    return suffix_clean_map.get(cleaned, "Other")

# Apply cleaning
df["Cleaned Suffix"] = df["Street Suffix"].apply(clean_suffix)

print(df[["Street Suffix", "Cleaned Suffix"]].drop_duplicates().head(30))

            Street Suffix Cleaned Suffix
159317                NaN        Unknown
159339                 St         Street
159354                 Pl          Place
159416                 Rd           Road
159558                Ave         Avenue
159567            Terrace        Terrace
160062                 Ct          Court
160085                  E          Other
160086                  W          Other
160217                 Dr          Drive
160224               Park           Park
160585                Way            Way
160594                 Pi          Other
160882                 Sq         Square
161699            Parkway          Other
162125            Circuit          Other
162652               Blvd      Boulevard
162963               Mall           Mall
163433             Street         Street
163434             Avenue         Avenue
163445              Drive          Drive
163449              place          Place
163450               Road           Road
164845      Dalton Street          Other
164846      Emerson Place          Other
164847        Everett St.          Other
164848        Portina Rd.          Other
164849       Portina Road          Other
164850    Washington Mall          Other
164851  Chestnut Hill Ave          Other

In [33]:
df.head()

,Street #,Street Name,Street Suffix,Unit #,Zip,7. undergraduate (u) or graduate (g),8. full-time (ft) or part-time (pt),9. at-home or not-at-home,9. 5 or more undergrads/unit (y/n),university,year,Cleaned Suffix
159317,10,Rhoda St,NaN,NaN,02132,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024,Unknown
159318,10,Rhoda Street,NaN,NaN,02132,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024,Unknown
159319,580,Washington Street,NaN,NaN,02111,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024,Unknown
159320,12,Sutherland Rd,NaN,3,02135,U,Full Time,Not-at-Home,NaN,BC-Woods College,2023-2024,Unknown
159321,137,Chiswick rd,NaN,apt 5,02135,U,Part Time,Not-at-Home,NaN,BC-Woods College,2023-2024,Unknown

In [38]:
import pandas as pd
from rapidfuzz import fuzz, process  # faster than fuzzywuzzy

# Example student housing data (df)
# Assume df already has these columns and cleaned_suffix is available
# Let's assume df and registry_df are loaded DataFrames

# 1. Build address strings from df
def build_combined_address(row):
    parts = [str(row["Street #"]), row["Street Name"]]
    if row["Cleaned Suffix"] not in ["Unknown", "Other"]:
        parts.append(row["Cleaned Suffix"])
    if pd.notna(row["Unit #"]):
        parts.append(str(row["Unit #"]))
    parts.append(row["Zip"])
    return ' '.join(parts)

df["Combined Address"] = df.apply(build_combined_address, axis=1).str.upper().str.strip()

# 2. Prepare registry addresses
registry_df["Registry Address"] = registry_df["Registry Address"].str.upper().str.strip()

# 3. Fuzzy match function
def match_address(addr, registry_addresses, threshold=90):
    match, score, _ = process.extractOne(addr, registry_addresses, scorer=fuzz.ratio)
    return match if score >= threshold else None

# 4. Apply matching
registry_address_list = registry_df["Registry Address"].tolist()
df["Matched Address"] = df["Combined Address"].apply(lambda x: match_address(x, registry_address_list))

# 5. Create matched and unmatched DataFrames
matched_df = df[df["Matched Address"].notna()].copy()
unmatched_df = df[df["Matched Address"].isna()].copy()

# 6. Show result
print("✅ Matched Addresses:")
print(matched_df[["Combined Address", "Matched Address"]].head())

print("\n❌ Unmatched Addresses:")
print(unmatched_df["Combined Address"].head())

TypeError: sequence item 1: expected str instance, float found

In [56]:
import re

def extract_street_only(address):
    """
    Extract the part of the address before the first comma,
    which should just be the street.
    """
    if pd.isna(address):
        return ""
    return address.split(',')[0].strip().upper()
registry_list = registry["RegisteredAddress"].apply(extract_street_only).tolist()

In [ ]:
df_subset = df.head(100).copy()

In [57]:
import pandas as pd
from fuzzywuzzy import fuzz, process

# 1. Build combined address from your DataFrame
def build_combined_address(row):
    parts = []
    
    if pd.notna(row["Street #"]):
        parts.append(str(row["Street #"]))
    
    if pd.notna(row["Street Name"]):
        parts.append(str(row["Street Name"]))
    
    if pd.notna(row["Cleaned Suffix"]) and row["Cleaned Suffix"] not in ["Unknown", "Other"]:
        parts.append(str(row["Cleaned Suffix"]))
    
    if pd.notna(row["Unit #"]):
        parts.append(str(row["Unit #"]))
    
    if pd.notna(row["Zip"]):
        parts.append(str(row["Zip"]))
    
    return ' '.join(parts)


df["Combined Address"] = df.apply(build_combined_address, axis=1).str.upper().str.strip()

# 2. Clean registry address column
registry["RegisteredAddress"] = registry["RegisteredAddress"].str.upper().str.strip()

# 3. Match function using fuzzywuzzy
def match_address(addr, registry_addresses, threshold=90):
    match = process.extractOne(addr, registry_addresses, scorer=fuzz.token_sort_ratio)
    if match and match[1] >= threshold:
        return match[0]
    return None

# 4. Apply matching
registry_list = registry["RegisteredAddress"].tolist()
df_subset["Matched Address"] = df_subset["Combined Address"].apply(lambda x: match_address(x, registry_list))


matched_df = df_subset[df_subset["Matched Address"].notna()].copy()
unmatched_df = df_subset[df_subset["Matched Address"].isna()].copy()

# 6. Output some results
print("✅ Matched Addresses:")
print(matched_df[["Combined Address", "Matched Address"]].head())

print("\n❌ Unmatched Addresses:")
print(unmatched_df["Combined Address"].head())

✅ Matched Addresses:
Empty DataFrame
Columns: [Combined Address, Matched Address]
Index: []

❌ Unmatched Addresses:
159317              10 RHODA ST 02132
159318          10 RHODA STREET 02132
159319    580 WASHINGTON STREET 02111
159320       12 SUTHERLAND RD 3 02135
159321    137 CHISWICK RD APT 5 02135
Name: Combined Address, dtype: object

In [53]:
print(df_subset["Combined Address"].head(5).tolist())

['10 RHODA ST 02132', '10 RHODA STREET 02132', '580 WASHINGTON STREET 02111', '12 SUTHERLAND RD 3 02135', '137 CHISWICK RD APT 5 02135']

In [54]:
print(registry_list[:5])

['54 DESOTO RD  , WEST ROXBURY, MA 02132', '152H CHESTNUT AV  , JAMAICA PLAIN, MA 02130', '103 NINTH ST  , CHARLESTOWN, MA 02129', '103 NINTH ST  , CHARLESTOWN, MA 02129', ',  , MA']